before_script:
  - ruby -v
  - bundle install

ruby-2.3:
  image: rails-lts:test-env
  services:
  - name: rails-lts:pg-9.1
    alias: pg-db
  - name: rails-lts:mysql-5.6
    alias: mysql-db
  - name: memcached:1.5
    alias: memcached
  script:
    - bundle exec rake railslts:test
  variables:
    BUNDLE_GEMFILE: /rails/Gemfile.2.3
    BUNDLE_PATH: /bundle
    MYSQL_HOST: mysql-db
    MYSQL_USER: rails
    PG_HOST: pg-db
    PG_USER: rails
    MEMCACHE_HOST: memcached
